---
# REM: maunally install before using with
# $ ansible-galaxy install -r requirements.yml

- src: https://github.com/dheles/ansible-role-login-user
  name: login-user

- src: https://github.com/dheles/ansible-role-secure-ssh
  name: secure-ssh

- src: https://github.com/dheles/testup-ansible-role
  name: testup

- src: https://github.com/dheles/java-ansible-role
  name: java

- src: https://github.com/dheles/maven-ansible-role
  name: maven

- src: https://github.com/dheles/ant-ansible-role
  name: ant

- src: https://github.com/dheles/tomcat-ansible-role
  name: tomcat

- src: https://github.com/dheles/ansible-role-postgres
  name: postgres
