#!/usr/bin/env python

import subprocess
import re

debugging = False

# git a list of staged files
result = subprocess.check_output("git diff HEAD --name-only --cached", shell=True, universal_newlines=True)
staged = result.split()
if debugging: print("staged: {}".format(staged))

unencrypted = []
for filename in staged:
    if "vault" in filename:
        if debugging: print("checking {}".format(filename))
        fh = open(filename)
        for line in fh:
            match = re.search('ANSIBLE_VAULT', line)
            if not match:
                unencrypted.append(fh.name)
                break
            else:
                if debugging: print("{} is ok".format(fh.name))
                break

if len(unencrypted) > 0:
    print("ERROR - cannot commit. the following vault files are unencrypted: ")
    for filename in unencrypted:
        print(filename)
    exit(1)
