---
tomcat_minimum_java_version:  1.7
tomcat_major_version:         8
tomcat_minor_version:         5
tomcat_patch_version:         43
tomcat_version:               "{{ tomcat_major_version }}.{{ tomcat_minor_version }}.{{ tomcat_patch_version }}"
tomcat_install_dir:           "/usr/local"
tomcat_download_dir:          "{{ ansible_env.HOME}}"
tomcat_dir:                   "apache-tomcat-{{ tomcat_version }}"
tomcat_download_file:         "{{ tomcat_dir }}.tar.gz"
tomcat_url:                   "https://archive.apache.org/dist/tomcat/tomcat-{{ tomcat_major_version }}/v{{ tomcat_version }}/bin/{{ tomcat_download_file }}"
tomcat_checksum_algo:         "sha1"
tomcat_checksum_url:          "{{ tomcat_url }}.{{ tomcat_checksum_algo }}"
tomcat_user:                  "{{ app_user      | default('tomcat') }}"
tomcat_group:                 "{{ app_group     | default(tomcat_user) }}"
tomcat_user_uid:              "{{ app_user_uid  | default(omit) }}"
tomcat_group_gid:             "{{ app_group_gid | default(omit) }}"
catalina_home:                "{{ tomcat_install_dir }}/tomcat"
java_home:                    "/usr/lib/jvm/jre"
tomcat_reinstall:             false
java_opts:                    "-Djava.awt.headless=true -Dfile.encoding=UTF-8"
catalina_opts:                "-server
                              -Xms256m
                              -Xmx512m
                              -XX:+UseParallelGC"
tomcat_manager_access:        true
tomcat_roles:
  - "manager-gui"
  - "admin-gui"
tomcat_users:
  - username: "admin"
    password: "changeme"
    roles:    "manager-gui,admin-gui"
tomcat_ip_whitelist:
  - "{{ internal_ip_regex }}"
tomcat_manager_configs:
  - "webapps/manager/META-INF/context.xml"
  - "webapps/host-manager/META-INF/context.xml"
