---
- name: include os-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

# TODO: cover all 7 formats: https://www.postgresql.org/docs/9.3/static/auth-pg-hba-conf.html
# vars:
# - (connection) type
# - database
# - user
# - address (localhost, ip, or fqdn)
# - (auth) method
# NOTE: the regex_replace adds a needed subnet mask to an unmasked ip address
- name: adjust pg_hba.conf for connection
  lineinfile:
    dest:         "{{ postgres_data_directory }}/pg_hba.conf"
    regexp:       "^{{ type }}\\s+{{ database }}\\s+{{ user }}\\s+{{ address | default('') | regex_replace('^(?P<ip>(?:[0-9]{1,3}\\.){3}[0-9]{1,3})$', '\\g<ip>/32') }}\\s+{{ method }}"
    line:         "{{ type }}   {{ database }}   {{ user }}   {{ address | default('') | regex_replace('^(?P<ip>(?:[0-9]{1,3}\\.){3}[0-9]{1,3})$', '\\g<ip>/32') }}   {{ method }}"
    state:        "{{ state }}"
    insertbefore: BOF
  become: true
  become_user: "{{ postgres_admin_user }}"
  notify: reload postgresql

# NOTE: while this can be a bit redundant, it's needed for db_refresh playbooks
# (at least as i currently write them)
# - meta: flush_handlers
