---
# encrypt a provided password for use with the user module

- name: install the Passlib password hashing library
  pip:
    name: ['passlib', 'argparse']
  delegate_to: 127.0.0.1

- name: execute encrypt password script
  script: encrypt_password.py -p {{ password }} -e {{ environ }}
  args:
    executable: python3
  delegate_to: 127.0.0.1
