- name: gather facts
  setup:
  register: facts

# verbosity level of 3 requires the play to be run with -vvv to output the debug data
- name: report facts
  debug:
    var: facts
    verbosity: 3

- name: report value of requested vars
  debug:
    msg: "{{ item }}"
  with_items: "{{ role_vars }}"
